// Mocks generated by Mockito 5.3.2 from annotations
// in mi_learning/test/features/auth/domain/usecase/sign_up_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mi_learning/app/auth/domain/repository/auth_repository.dart'
    as _i3;
import 'package:mi_learning/app/auth/domain/usecase/forget_password_use_case.dart'
    as _i8;
import 'package:mi_learning/app/auth/domain/usecase/sign_in_request_params.dart'
    as _i6;
import 'package:mi_learning/app/auth/domain/usecase/sign_up_request_params.dart'
    as _i7;
import 'package:mi_learning/base/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> emailPasswordFirebaseSignIn(
          _i6.SignInRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #emailPasswordFirebaseSignIn,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #emailPasswordFirebaseSignIn,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> signIn(
          _i6.SignInRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #signIn,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, dynamic>> signUp(
          _i7.SignUpRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, dynamic>>.value(
            _FakeEither_0<_i5.Failure, dynamic>(
          this,
          Invocation.method(
            #signUp,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, dynamic>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> forgetPassword(
          _i8.ForgetPasswordParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #forgetPassword,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
