// Mocks generated by Mockito 5.3.2 from annotations
// in mi_learning/test/features/checkout/data/repositories/course_detail_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i11;
import 'package:mi_learning/app/common/domain/entity/course_entities/course.dart'
    as _i7;
import 'package:mi_learning/app/common/domain/entity/course_entities/rating.dart'
    as _i9;
import 'package:mi_learning/app/course_detail/data/datasources/course_detail_remote_data_source.dart'
    as _i5;
import 'package:mi_learning/app/course_detail/domain/usecases/submit_review_use_case.dart'
    as _i10;
import 'package:mi_learning/app/course_detail/domain/usecases/toggle_save_course_use_case.dart'
    as _i8;
import 'package:mi_learning/base/failure.dart' as _i3;
import 'package:mi_learning/base/models/response_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_1 extends _i1.SmartFake implements _i3.Failure {
  _FakeFailure_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResponse_2 extends _i1.SmartFake implements _i4.BaseResponse {
  _FakeBaseResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourseDetailRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseDetailRemoteDataSource extends _i1.Mock
    implements _i5.CourseDetailRemoteDataSource {
  MockCourseDetailRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i3.Failure, _i7.Course>> getCourseDetail(
          String? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseDetail,
          [courseId],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, _i7.Course>>.value(
            _FakeEither_0<_i3.Failure, _i7.Course>(
          this,
          Invocation.method(
            #getCourseDetail,
            [courseId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, _i7.Course>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, bool>> toggleSaveCourse(
          _i8.ToggleSaveCourseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleSaveCourse,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, bool>>.value(
            _FakeEither_0<_i3.Failure, bool>(
          this,
          Invocation.method(
            #toggleSaveCourse,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, bool>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, List<_i7.Course>>> getSavedCourses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedCourses,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i3.Failure, List<_i7.Course>>>.value(
                _FakeEither_0<_i3.Failure, List<_i7.Course>>(
          this,
          Invocation.method(
            #getSavedCourses,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, List<_i7.Course>>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, bool>> checkout(String? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkout,
          [courseId],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, bool>>.value(
            _FakeEither_0<_i3.Failure, bool>(
          this,
          Invocation.method(
            #checkout,
            [courseId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, bool>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, _i9.Rating>> createRating(
          _i10.SubmitReviewParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRating,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, _i9.Rating>>.value(
            _FakeEither_0<_i3.Failure, _i9.Rating>(
          this,
          Invocation.method(
            #createRating,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, _i9.Rating>>);
  @override
  _i3.Failure mapExceptionToFailure(Object? exception) => (super.noSuchMethod(
        Invocation.method(
          #mapExceptionToFailure,
          [exception],
        ),
        returnValue: _FakeFailure_1(
          this,
          Invocation.method(
            #mapExceptionToFailure,
            [exception],
          ),
        ),
      ) as _i3.Failure);
  @override
  _i6.Future<_i4.BaseResponse> get(
    String? endpoint, {
    String? host,
    Map<String, dynamic>? query,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #host: host,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #host: host,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> post(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> put(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
}
