// Mocks generated by Mockito 5.3.2 from annotations
// in mi_learning/test/features/checkout/presentation/providers/order_detail_page_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mi_learning/app/course_detail/domain/usecases/checkout_use_case.dart'
    as _i3;
import 'package:mi_learning/app/dashboard/domain/usecases/get_basic_user_info_use_case.dart'
    as _i6;
import 'package:mi_learning/app/user/domain/entities/basic_user_info.dart'
    as _i7;
import 'package:mi_learning/base/domain/usecase/params.dart' as _i8;
import 'package:mi_learning/base/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CheckoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckoutUseCase extends _i1.Mock implements _i3.CheckoutUseCase {
  MockCheckoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(_i3.CheckoutParam? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [GetBasicUserInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBasicUserInfoUseCase extends _i1.Mock
    implements _i6.GetBasicUserInfoUseCase {
  MockGetBasicUserInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.BasicUserInfo>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.BasicUserInfo>>.value(
                _FakeEither_0<_i5.Failure, _i7.BasicUserInfo>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.BasicUserInfo>>);
}
