// Mocks generated by Mockito 5.3.2 from annotations
// in mi_learning/test/features/auth/data/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i10;
import 'package:mi_learning/app/auth/data/datasources/auth_firebase_data_source.dart'
    as _i12;
import 'package:mi_learning/app/auth/data/datasources/auth_local_data_souce.dart'
    as _i11;
import 'package:mi_learning/app/auth/data/datasources/auth_remote_data_source.dart'
    as _i5;
import 'package:mi_learning/app/auth/domain/usecase/sign_in_request_params.dart'
    as _i8;
import 'package:mi_learning/app/auth/domain/usecase/sign_up_request_params.dart'
    as _i9;
import 'package:mi_learning/app/common/domain/entity/tokens.dart' as _i7;
import 'package:mi_learning/base/failure.dart' as _i3;
import 'package:mi_learning/base/models/response_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_1 extends _i1.SmartFake implements _i3.Failure {
  _FakeFailure_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResponse_2 extends _i1.SmartFake implements _i4.BaseResponse {
  _FakeBaseResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i3.Failure, _i7.Tokens>> signIn(
          _i8.SignInRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, _i7.Tokens>>.value(
            _FakeEither_0<_i3.Failure, _i7.Tokens>(
          this,
          Invocation.method(
            #signIn,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, _i7.Tokens>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, dynamic>> signUp(
          _i9.SignUpRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, dynamic>>.value(
            _FakeEither_0<_i3.Failure, dynamic>(
          this,
          Invocation.method(
            #signUp,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, dynamic>>);
  @override
  _i3.Failure mapExceptionToFailure(Object? exception) => (super.noSuchMethod(
        Invocation.method(
          #mapExceptionToFailure,
          [exception],
        ),
        returnValue: _FakeFailure_1(
          this,
          Invocation.method(
            #mapExceptionToFailure,
            [exception],
          ),
        ),
      ) as _i3.Failure);
  @override
  _i6.Future<_i4.BaseResponse> get(
    String? endpoint, {
    String? host,
    Map<String, dynamic>? query,
    _i10.Options? options,
    _i10.CancelToken? cancelToken,
    _i10.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #host: host,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #host: host,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> post(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i10.Options? options,
    _i10.CancelToken? cancelToken,
    _i10.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> put(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i10.Options? options,
    _i10.CancelToken? cancelToken,
    _i10.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i11.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> storeTokens(_i7.Tokens? tokens) => (super.noSuchMethod(
        Invocation.method(
          #storeTokens,
          [tokens],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [AuthFirebaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthFirebaseDataSource extends _i1.Mock
    implements _i12.AuthFirebaseDataSource {
  MockAuthFirebaseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i3.Failure, bool>> emailPasswordSignIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #emailPasswordSignIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, bool>>.value(
            _FakeEither_0<_i3.Failure, bool>(
          this,
          Invocation.method(
            #emailPasswordSignIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, bool>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, bool>> emailPasswordRegister(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #emailPasswordRegister,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, bool>>.value(
            _FakeEither_0<_i3.Failure, bool>(
          this,
          Invocation.method(
            #emailPasswordRegister,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, bool>>);
  @override
  _i6.Future<_i2.Either<_i3.Failure, bool>> forgetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i6.Future<_i2.Either<_i3.Failure, bool>>.value(
            _FakeEither_0<_i3.Failure, bool>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, bool>>);
}
