// Mocks generated by Mockito 5.3.2 from annotations
// in mi_learning/test/features/articles/data/repositories/article_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i8;
import 'package:mi_learning/app/article/data/datasources/article_remote_data_source.dart'
    as _i5;
import 'package:mi_learning/app/article/domain/entities/article.dart' as _i7;
import 'package:mi_learning/base/failure.dart' as _i3;
import 'package:mi_learning/base/models/response_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_1 extends _i1.SmartFake implements _i3.Failure {
  _FakeFailure_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResponse_2 extends _i1.SmartFake implements _i4.BaseResponse {
  _FakeBaseResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRemoteDataSource extends _i1.Mock
    implements _i5.ArticleRemoteDataSource {
  MockArticleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get getArticlesEndPoint => (super.noSuchMethod(
        Invocation.getter(#getArticlesEndPoint),
        returnValue: '',
      ) as String);
  @override
  _i6.Future<_i2.Either<_i3.Failure, List<_i7.Article>>> getArticles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i3.Failure, List<_i7.Article>>>.value(
                _FakeEither_0<_i3.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #getArticles,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i3.Failure, List<_i7.Article>>>);
  @override
  _i3.Failure mapExceptionToFailure(Object? exception) => (super.noSuchMethod(
        Invocation.method(
          #mapExceptionToFailure,
          [exception],
        ),
        returnValue: _FakeFailure_1(
          this,
          Invocation.method(
            #mapExceptionToFailure,
            [exception],
          ),
        ),
      ) as _i3.Failure);
  @override
  _i6.Future<_i4.BaseResponse> get(
    String? endpoint, {
    String? host,
    Map<String, dynamic>? query,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #host: host,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #host: host,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> post(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
  @override
  _i6.Future<_i4.BaseResponse> put(
    String? endpoint, {
    String? host,
    dynamic data,
    Map<String, dynamic>? query,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #host: host,
            #data: data,
            #query: query,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgres: onReceiveProgres,
          },
        ),
        returnValue: _i6.Future<_i4.BaseResponse>.value(_FakeBaseResponse_2(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #host: host,
              #data: data,
              #query: query,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgres: onReceiveProgres,
            },
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse>);
}
